### ISSUE TITLE
Port Olympic Games sample app to MVC project 

### ISSUE THREAD

**Issue by Iankodj** [telerik/olympic-games-sample-app-mvc#3]
Needed by telerik/kendo#6333. 

Tasks:

- [x] Prototype the Olympic Games MVC project #1
- [x] Add Olympics database #2 
- [x] Generate Web API controllers using EF + Models for Olympics database #4
- [x] Add Nuget for Kendo MVC #5
- [x] Implement the layout of the application (Use CDN for the resources needed) #6
- [x] Implement view for:
* - [x] Medals by Country #7
* - [x] Medals by Sport #8 
* - [x] Top Results by Sport #9
* - [x] Athlete Comparison #10
* - [x] About this sample app (Use info from Readme) #11
